version: "3.9"

services:
  django:
    build:
      dockerfile: Dockerfile
    container_name: diploma_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
    entrypoint: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  parser:
    build:
      dockerfile: DockerfileParser
    container_name: diploma_parser
    depends_on:
      django:
        condition: service_started
    restart: unless-stopped
    entrypoint: >
      bash -c "python parse.py"

  db:
    hostname: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=diplomaBackend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT 1;' | psql -U postgres -d diplomaBackend" ]
      interval: 3s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    driver: local
